name: Scheduled destroyer

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  destroy-branch:
    runs-on: self-hosted
    environment: develeopment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0
          ref: main

      - name: Git actions
        run: |
          ls -la
          git branch
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin --delete deploy
          git checkout -b deploy
          git push -u origin deploy